### PR TITLE
Added "SKEBBY_VERIFY_SSL_CERTIFICATE" setting.

### PR DESCRIPTION
**Pull request by ilCapo77**
Last week I had a small problem with the Skebby SSL certificate. For this reason I have made some changes. Perhaps it might be useful...

I added a new setting: SKEBBY_VERIFY_SSL_CERTIFICATE, to enable/disable the Skebby SSL certificate verification (default == False).

### CODE REVIEW

**Comment by xrmx** [comment]
Thanks for the pull request! Looks good, except the ssl one. I'd make the default for SKEBBY_VERIFY_SSL_CERTIFICATE to True as it should be safe by default. Do you need the change because of too old python? or their ssl cert has issues?

**Comment by ilCapo77** [comment]
Ok. I will make this setting True as default.
I'm quite sure that the problem was in their SSL certificate (expired???). My webapp was in production since months with python 2.7.6 and django 1.7.
In any case. I solved this issue quickly with this patch.

**Comment by xrmx** [comment]
Thanks, merged!

**Comment by xrmx** [comment]
FYI Just released django-skebby 0.3.1 and uploaded to pip

**Pull request closed without merging**
